name: Build and Push to ECR (Manual)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: aws-deploy
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}
      IMAGE_NAME: ml_ops/clima
      DOCKERFILE_PATH: Dockerfile
      BUILD_CONTEXT: .
      IMAGE_TAG: latest
      ECR_REGISTRY: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      GIT_SHA_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Access Keys)
        if: ${{ secrets.AWS_ACCESS_KEY_ID != '' && secrets.AWS_SECRET_ACCESS_KEY != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        run: |
          set -e
          REPO="${IMAGE_NAME}"
          if ! aws ecr describe-repositories --repository-names "$REPO" >/dev/null 2>&1; then
            aws ecr create-repository --repository-name "$REPO" >/dev/null
            echo "Repository $REPO created."
          else
            echo "Repository $REPO already exists."
          fi

      - name: Build image
        run: |
          docker build \
            -f "$DOCKERFILE_PATH" \
            -t "${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}" \
            -t "${ECR_REGISTRY}/${IMAGE_NAME}:${GIT_SHA_TAG}" \
            "$BUILD_CONTEXT"

      - name: Push image
        run: |
          docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${GIT_SHA_TAG}"

      - name: Output image URIs
        run: |
          echo "${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
          echo "${ECR_REGISTRY}/${IMAGE_NAME}:${GIT_SHA_TAG}"
