name: Climate Prediction Scheduler

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    environment: aws

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_BUCKET_OUTPUT: ${{ secrets.AWS_BUCKET_OUTPUT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

      AWS_JOBLIB_ACCESS_KEY: ${{ secrets.AWS_JOBLIB_ACCESS_KEY }}
      AWS_JOBLIB_SECRET_KEY: ${{ secrets.AWS_JOBLIB_SECRET_KEY }}
      AWS_JOBLIB_BUCKET: ${{ secrets.AWS_JOBLIB_BUCKET }}
      AWS_JOBLIB_REGION: ${{ secrets.AWS_JOBLIB_REGION }}
      AWS_MODELS_PATH: ${{ secrets.AWS_MODELS_PATH }}
      
      DATA_PATH_FORMAT: ${{ secrets.DATA_PATH_FORMAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Climate Prediction Pipeline
        run: |
          python models/model.py
